#include "water_adc.h"

extern ADC_HandleTypeDef hadc1;

#define WATER_ADC_VREF_MV      3300UL
#define WATER_ADC_MAX_COUNT    4095UL
#define WATER_ADC_CHANNEL      ADC_CHANNEL_10
#define POWER_ADC_CHANNEL      ADC_CHANNEL_12
#define POWER_DIVIDER_HIGH_KOHM 100UL
#define POWER_DIVIDER_LOW_KOHM  10UL

static uint8_t water_adc_calibrated = 0U;

static uint16_t ADC_Read_Channel(uint32_t channel)
{
    ADC_ChannelConfTypeDef sConfig = {0};
    uint16_t value;

    value = 0U;
    (void)HAL_ADC_Stop(&hadc1);

    sConfig.Channel = channel;
    sConfig.Rank = ADC_REGULAR_RANK_1;
    sConfig.SamplingTime = ADC_SAMPLETIME_64CYCLES_5;
    sConfig.SingleDiff = ADC_SINGLE_ENDED;
    sConfig.OffsetNumber = ADC_OFFSET_NONE;
    sConfig.Offset = 0;
    sConfig.OffsetSignedSaturation = DISABLE;
    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
    {
        return 0U;
    }

    if (HAL_ADC_Start(&hadc1) == HAL_OK)
    {
        if (HAL_ADC_PollForConversion(&hadc1, 10U) == HAL_OK)
        {
            value = (uint16_t)HAL_ADC_GetValue(&hadc1);
        }
        (void)HAL_ADC_Stop(&hadc1);
    }

    return value;
}

void Myadc_Init(void)
{
    /* ADC1 base config is generated by CubeMX; each read selects its own channel. */
    if (water_adc_calibrated == 0U)
    {
        if (HAL_ADCEx_Calibration_Start(&hadc1, ADC_CALIB_OFFSET, ADC_SINGLE_ENDED) == HAL_OK)
        {
            water_adc_calibrated = 1U;
        }
    }
}

uint16_t Water_Get_AnalogRaw(void)
{
    return ADC_Read_Channel(WATER_ADC_CHANNEL);
}

uint16_t Get_ADC_Value(void)
{
    return Water_Get_AnalogRaw();
}

uint32_t Water_RawToVoltageMv(uint16_t raw)
{
    return ((uint32_t)raw * WATER_ADC_VREF_MV + (WATER_ADC_MAX_COUNT / 2UL)) / WATER_ADC_MAX_COUNT;
}

uint32_t Water_Get_AnalogVoltageMv(void)
{
    return Water_RawToVoltageMv(Water_Get_AnalogRaw());
}

uint16_t Power_Get_AdcRaw(void)
{
    return ADC_Read_Channel(POWER_ADC_CHANNEL);
}

uint32_t Power_RawToAdcVoltageMv(uint16_t raw)
{
    return Water_RawToVoltageMv(raw);
}

uint32_t Power_RawToInputVoltageMv(uint16_t raw)
{
    uint32_t adc_mv;

    adc_mv = Power_RawToAdcVoltageMv(raw);
    return (adc_mv * (POWER_DIVIDER_HIGH_KOHM + POWER_DIVIDER_LOW_KOHM)
            + (POWER_DIVIDER_LOW_KOHM / 2UL)) / POWER_DIVIDER_LOW_KOHM;
}

uint32_t Power_Get_InputVoltageMv(void)
{
    return Power_RawToInputVoltageMv(Power_Get_AdcRaw());
}

uint8_t Water_Get_Digital(void)
{
    return (HAL_GPIO_ReadPin(WATER_DO_GPIO_Port, WATER_DO_Pin) == GPIO_PIN_SET) ? 1U : 0U;
}

uint8_t Water_Is_Wet(void)
{
    return (HAL_GPIO_ReadPin(WATER_DO_GPIO_Port, WATER_DO_Pin) == WATER_DO_WET_LEVEL) ? 1U : 0U;
}
